apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: webapp
  labels:
    app: webapp
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: webapp-php
          image: webapp-php:v0.1.2
          imagePullPolicy: Never
        - name: webapp-nginx
          image: webapp-nginx:v0.1.2
          imagePullPolicy: Never
